package ai.takeoff.insightscompanion

import android.content.Context
import org.json.JSONArray
import org.json.JSONObject

class LocalInsightStore(context: Context) {
    data class TimelinePoint(val at: Long, val metrics: Map<String, Double>)
    data class Reel(val accountId: String,val shortcode: String,val url: String,val scenarioId: String?,val firstSeenAt: Long,val lastCaptureAt: Long,val executionFidelity: String,val metrics: Map<String, Double>,val state: String,val timeline: List<TimelinePoint>)
    data class PlannedScenario(val scenarioId: String, val title: String, val accountId: String, val createdAt: Long)
    companion object {
        internal fun finiteMetrics(obj: JSONObject?): Map<String, Double> { if (obj == null) return emptyMap(); val metrics = linkedMapOf<String, Double>(); val keys = obj.keys(); while (keys.hasNext()) { val key = keys.next(); if (obj.isNull(key)) continue; val value = when (val raw = obj.opt(key)) { is Number -> raw.toDouble(); is String -> raw.trim().toDoubleOrNull(); else -> null } ?: continue; if (value.isFinite()) metrics[key] = value }; return metrics }
    }
    private val secret = SecretStore(context)
    fun armReel(accountId: String, shortcode: String, url: String) { val reels = readReels(); val key = "$accountId::$shortcode"; val now = System.currentTimeMillis(); val previous = reels.optJSONObject(key); val obj = previous ?: JSONObject().put("first_seen_at", now); obj.put("account_id", accountId).put("shortcode", shortcode).put("url", url).put("state", "armed"); reels.put(key, obj); writeReels(reels) }
    fun bindScenario(accountId: String, shortcode: String, scenarioId: String?) { val reels = readReels(); val key = "$accountId::$shortcode"; val obj = reels.optJSONObject(key) ?: return; if (scenarioId.isNullOrBlank()) obj.remove("scenario_id") else obj.put("scenario_id", scenarioId.trim()); reels.put(key, obj); writeReels(reels) }
    fun markCapture(payload: JSONObject, state: String = "queued") { val account = payload.optString("account_id"); val shortcode = payload.optString("shortcode"); if (account.isBlank() || shortcode.isBlank()) return; val reels = readReels(); val key = "$account::$shortcode"; val now = System.currentTimeMillis(); val obj = reels.optJSONObject(key) ?: JSONObject().put("account_id", account).put("shortcode", shortcode).put("url", payload.optString("url")).put("first_seen_at", now); obj.put("last_capture_at", now).put("state", state).put("execution_fidelity", payload.optString("execution_fidelity", "unknown")); payload.optString("scenario_id").takeIf { it.isNotBlank() }?.let { obj.put("scenario_id", it) }; val metric = JSONObject(); finiteMetrics(payload.optJSONObject("metrics")).forEach { (name, value) -> metric.put(name, value) }; obj.put("metrics", metric); val timeline = obj.optJSONArray("timeline") ?: JSONArray(); timeline.put(JSONObject().put("at", now).put("metrics", metric)); while (timeline.length() > 24) timeline.remove(0); obj.put("timeline", timeline); reels.put(key, obj); writeReels(reels) }
    fun updateState(accountId: String, shortcode: String, state: String) { val reels = readReels(); val key = "$accountId::$shortcode"; val obj = reels.optJSONObject(key) ?: return; obj.put("state", state); reels.put(key, obj); writeReels(reels) }
    fun reels(accountId: String? = null): List<Reel> { val src = readReels(); val out = mutableListOf<Reel>(); val keys = src.keys(); while (keys.hasNext()) { val obj = src.optJSONObject(keys.next()) ?: continue; val account = obj.optString("account_id"); if (!accountId.isNullOrBlank() && account != accountId) continue; val metrics = finiteMetrics(obj.optJSONObject("metrics")); val timeline = mutableListOf<TimelinePoint>(); val rawTimeline = obj.optJSONArray("timeline") ?: JSONArray(); for (i in 0 until rawTimeline.length()) { val point = rawTimeline.optJSONObject(i) ?: continue; timeline += TimelinePoint(point.optLong("at"), finiteMetrics(point.optJSONObject("metrics"))) }; out += Reel(account, obj.optString("shortcode"), obj.optString("url"), obj.optString("scenario_id").takeIf { it.isNotBlank() }, obj.optLong("first_seen_at"), obj.optLong("last_capture_at"), obj.optString("execution_fidelity", "unknown"), metrics, obj.optString("state", "armed"), timeline.sortedBy { it.at }) }; return out.sortedByDescending { maxOf(it.lastCaptureAt, it.firstSeenAt) } }
    fun addScenario(accountId: String, scenarioId: String, title: String) { require(scenarioId.trim().isNotBlank()); val arr = readScenarios(); val next = JSONArray(); val id = scenarioId.trim(); for (i in 0 until arr.length()) { val item = arr.optJSONObject(i) ?: continue; if (item.optString("scenario_id") != id) next.put(item) }; next.put(JSONObject().put("scenario_id", id).put("title", title.trim()).put("account_id", accountId).put("created_at", System.currentTimeMillis())); secret.put("planned_scenarios", next.toString()) }
    fun scenarios(accountId: String? = null): List<PlannedScenario> { val arr = readScenarios(); val out = mutableListOf<PlannedScenario>(); for (i in 0 until arr.length()) { val o = arr.optJSONObject(i) ?: continue; val account = o.optString("account_id"); if (!accountId.isNullOrBlank() && account != accountId) continue; out += PlannedScenario(o.optString("scenario_id"), o.optString("title"), account, o.optLong("created_at")) }; return out.sortedByDescending { it.createdAt } }
    fun removeScenario(id: String) { val arr = readScenarios(); val next = JSONArray(); for (i in 0 until arr.length()) { val item = arr.optJSONObject(i) ?: continue; if (item.optString("scenario_id") != id) next.put(item) }; secret.put("planned_scenarios", next.toString()) }
    private fun readReels() = runCatching { JSONObject(secret.get("local_reel_index") ?: "{}") }.getOrElse { JSONObject() }
    private fun writeReels(value: JSONObject) = secret.put("local_reel_index", value.toString())
    private fun readScenarios() = runCatching { JSONArray(secret.get("planned_scenarios") ?: "[]") }.getOrElse { JSONArray() }
}
