package ai.takeoff.insightscompanion

import java.text.Normalizer
import java.util.Locale
import kotlin.math.abs
import kotlin.math.max

object MetricParser {
    data class OcrLine(val text: String, val left: Int, val top: Int, val right: Int, val bottom: Int)
    private val aliases = linkedMapOf(
        "views" to listOf("views", "plays", "بازدید", "بازدیدها"), "viewers" to listOf("viewers", "unique viewers", "بینندگان"), "reach" to listOf("accounts reached", "reach", "حساب های دسترسی یافته", "حساب‌های دسترسی‌یافته", "دسترسی"), "likes" to listOf("likes", "پسند", "لایک"), "comments" to listOf("comments", "نظر", "نظرات", "کامنت"), "reposts" to listOf("reposts", "بازنشر"), "shares" to listOf("shares", "اشتراک گذاری", "اشتراک‌گذاری", "ارسال"), "saves" to listOf("saves", "ذخیره", "ذخیره ها", "ذخیره‌ها"), "follows" to listOf("follows", "followers gained", "دنبال کننده", "دنبال‌کننده", "فالو"), "profile_visits" to listOf("profile visits", "profile activity", "بازدید پروفایل", "فعالیت پروفایل"), "avg_watch_time_seconds" to listOf("average watch time", "avg watch time", "میانگین زمان تماشا", "میانگین زمان مشاهده"), "total_watch_time_seconds" to listOf("total watch time", "watch time", "زمان تماشا", "زمان مشاهده"), "completion_rate" to listOf("completion rate", "watched full reel", "نرخ تکمیل", "تا انتها"), "hold_3s_rate" to listOf("3-second view rate", "3 second view rate", "3s hold", "۳ ثانیه", "سه ثانیه"), "replay_rate" to listOf("replay rate", "replays", "بازپخش", "تکرار مشاهده"), "skip_rate" to listOf("skip rate", "نرخ رد کردن"), "share_rate" to listOf("share rate", "نرخ اشتراک گذاری", "نرخ اشتراک‌گذاری"), "like_rate" to listOf("like rate", "نرخ لایک", "نرخ پسند"), "save_rate" to listOf("save rate", "نرخ ذخیره"), "repost_rate" to listOf("repost rate", "نرخ بازنشر"), "comment_rate" to listOf("comment rate", "نرخ نظر", "نرخ کامنت"), "audience_followers_rate" to listOf("followers", "دنبال کنندگان", "دنبال‌کنندگان"), "audience_nonfollowers_rate" to listOf("non-followers", "non followers", "غیردنبال کنندگان", "غیردنبال‌کنندگان"), "source_reels_tab_rate" to listOf("reels tab", "تب reels", "تب ریلز"), "source_explore_rate" to listOf("explore", "اکسپلور"), "source_feed_rate" to listOf("feed", "فید"), "source_stories_rate" to listOf("stories", "استوری"), "source_profile_rate" to listOf("profile", "پروفایل"), "age_13_17_rate" to listOf("13-17", "۱۳-۱۷"), "age_18_24_rate" to listOf("18-24", "۱۸-۲۴"), "age_25_34_rate" to listOf("25-34", "۲۵-۳۴"), "age_35_44_rate" to listOf("35-44", "۳۵-۴۴"), "age_45_54_rate" to listOf("45-54", "۴۵-۵۴"), "age_55_64_rate" to listOf("55-64", "۵۵-۶۴"), "age_65_plus_rate" to listOf("65+", "۶۵+")
    )
    private val countFields = setOf("views", "viewers", "reach", "likes", "comments", "reposts", "shares", "saves", "follows", "profile_visits")
    fun parse(ocrText: String): Map<String, Double> { val lines = ocrText.lines().map { normalize(it) }.filter { it.isNotBlank() }; val out = linkedMapOf<String, Double>(); for ((field, names) in aliases) { val idx = lines.indexOfFirst { line -> matchesField(field, line, names) }; if (idx < 0) continue; val window = lines.subList(idx, minOf(lines.size, idx + 2)).joinToString(" "); val value = parseValue(field, window); if (value != null) out[field] = value }; return out }
    fun parseStructured(ocrLines: List<OcrLine>): Map<String, Double> { val lines = ocrLines.map { it.copy(text = normalize(it.text)) }.filter { it.text.isNotBlank() }; val out = linkedMapOf<String, Double>(); for ((field, names) in aliases) { val labels = lines.filter { matchesField(field, it.text, names) }; var best: Pair<Double, Double>? = null; for (label in labels) { val sameLine = parseValueAfterAlias(field, label.text, names); if (sameLine != null) { best = 0.0 to sameLine; break }; val labelHeight = max(1, label.bottom - label.top); val labelWidth = max(1, label.right - label.left); val labelCx = (label.left + label.right) / 2.0; val candidates = lines.asSequence().filter { it.top >= label.top - labelHeight }.filter { it.top - label.bottom <= max(320, labelHeight * 8) }.filter { !containsAnyAlias(it.text) }.mapNotNull { candidate -> val value = parseValue(field, candidate.text) ?: return@mapNotNull null; val overlap = max(0, minOf(label.right, candidate.right) - maxOf(label.left, candidate.left)); val candidateWidth = max(1, candidate.right - candidate.left); val overlapRatio = overlap.toDouble() / minOf(labelWidth, candidateWidth).toDouble(); val cx = (candidate.left + candidate.right) / 2.0; val centerDistance = abs(cx - labelCx); val sameRow = abs(candidate.top - label.top) <= labelHeight * 2; if (!sameRow && overlapRatio < 0.20 && centerDistance > max(labelWidth, candidateWidth) * 0.65) return@mapNotNull null; val verticalGap = max(0, candidate.top - label.bottom); val score = verticalGap + centerDistance * (if (sameRow) 0.08 else 0.35) - overlapRatio * 40.0; score to value }.sortedBy { it.first }.firstOrNull(); if (candidates != null && (best == null || candidates.first < best!!.first)) best = candidates }; if (best != null) out[field] = best!!.second }; return out }
    private fun matchesField(field: String, line: String, names: List<String>): Boolean { val aliasMatch = names.any { alias -> line.contains(normalize(alias)) }; if (!aliasMatch) return false; if (field in countFields && (line.contains(" rate") || line.contains("نرخ "))) return false; if (field == "audience_followers_rate" && (line.contains("non-follow") || line.contains("غیردنبال"))) return false; if (field == "source_profile_rate" && line.contains("profile visits")) return false; return if (field == "total_watch_time_seconds") !(line.contains("average") || line.contains("avg") || line.contains("میانگین")) else true }
    private fun containsAnyAlias(line: String): Boolean = aliases.values.flatten().any { line.contains(normalize(it)) }
    private fun parseValueAfterAlias(field: String, line: String, names: List<String>): Double? { for (alias in names.map(::normalize).sortedByDescending { it.length }) { val idx = line.indexOf(alias); if (idx < 0) continue; val tail = line.substring(idx + alias.length).trim(); if (tail.isNotBlank()) parseValue(field, tail)?.let { return it } }; return null }
    private fun parseValue(field: String, text: String): Double? = if (field.endsWith("_seconds")) parseDuration(text) else parseNumberOrRate(text, field.endsWith("_rate"))
    private fun normalize(raw: String): String = Normalizer.normalize(raw, Normalizer.Form.NFKC).replace('ي', 'ی').replace('ك', 'ک').replace('٫', '.').replace('٬', ',').replace('٪', '%').replace('％', '%').lowercase(Locale.ROOT).trim()
    private fun parseNumberOrRate(text: String, rate: Boolean): Double? { val percent = Regex("([0-9۰-۹٠-٩]+(?:[.,][0-9۰-۹٠-٩]+)?)\\s*%").find(text); if (percent != null) return digits(percent.groupValues[1]).replace(",", "").toDoubleOrNull()?.div(100.0); if (rate) return null; val m = Regex("([0-9۰-۹٠-٩]+(?:[.,][0-9۰-۹٠-٩]+)?)\\s*([kKmMbB])?").findAll(text).toList().lastOrNull() ?: return null; val base = digits(m.groupValues[1]).replace(",", "").toDoubleOrNull() ?: return null; val mult = when (m.groupValues[2].lowercase()) { "k" -> 1_000.0; "m" -> 1_000_000.0; "b" -> 1_000_000_000.0; else -> 1.0 }; return base * mult }
    private fun parseDuration(text: String): Double? { val h = Regex("([0-9۰-۹٠-٩]+)\\s*(h|hr|hour|ساعت)").find(text)?.groupValues?.get(1)?.let(::digits)?.toDoubleOrNull() ?: 0.0; val m = Regex("([0-9۰-۹٠-٩]+)\\s*(m|min|minute|دقیقه)").find(text)?.groupValues?.get(1)?.let(::digits)?.toDoubleOrNull() ?: 0.0; val s = Regex("([0-9۰-۹٠-٩]+(?:[.,][0-9۰-۹٠-٩]+)?)\\s*(s|sec|second|seconds|ثانیه)").find(text)?.groupValues?.get(1)?.let(::digits)?.replace(",", "")?.toDoubleOrNull() ?: 0.0; if (h + m + s > 0) return h * 3600 + m * 60 + s; return parseNumberOrRate(text, false) }
    private fun digits(value: String): String { val fa = "۰۱۲۳۴۵۶۷۸۹"; val ar = "٠١٢٣٤٥٦٧٨٩"; return buildString { for (c in value) append(when { fa.indexOf(c) >= 0 -> ('0'.code + fa.indexOf(c)).toChar(); ar.indexOf(c) >= 0 -> ('0'.code + ar.indexOf(c)).toChar(); else -> c }) } }
}
