package ai.takeoff.insightscompanion

import android.app.NotificationChannel
import android.app.NotificationManager
import android.app.PendingIntent
import android.content.Context
import android.content.Intent
import android.net.Uri
import androidx.core.app.NotificationCompat
import androidx.work.Worker
import androidx.work.WorkerParameters
import org.json.JSONObject

class PendingWorker(appContext: Context, params: WorkerParameters) : Worker(appContext, params) {
    companion object { private const val CHANNEL = "takeoff_insights_due_v2"; private const val MAX_NOTIFICATIONS_PER_RUN = 5; private const val REMINDER_PREFS = "takeoff_companion_reminders"; private const val SHOWN_KEYS = "shown_window_keys" }
    override fun doWork(): Result {
        val prefs = applicationContext.getSharedPreferences("takeoff_companion_plain", Context.MODE_PRIVATE); val endpoint = prefs.getString("endpoint", "").orEmpty(); val key = SecretStore(applicationContext).get("api_key").orEmpty(); if (endpoint.isBlank() || key.isBlank()) return Result.success()
        val accounts = ManagedAccountStore(applicationContext).all().map { it.normalizedHandle }.filter { it.isNotBlank() }.distinct(); if (accounts.isEmpty()) return Result.success()
        val reminderPrefs = applicationContext.getSharedPreferences(REMINDER_PREFS, Context.MODE_PRIVATE); val shown = reminderPrefs.getStringSet(SHOWN_KEYS, emptySet()).orEmpty().toMutableSet(); var notified = 0; var transientFailure = false; var shownChanged = false; var cappedBacklog = false
        fun persistShownIfNeeded(): Boolean { if (!shownChanged) return true; val persisted = reminderPrefs.edit().putStringSet(SHOWN_KEYS, shown.toSet()).commit(); if (persisted) shownChanged = false; return persisted }
        return try { for ((accountIndex, account) in accounts.withIndex()) { if (notified >= MAX_NOTIFICATIONS_PER_RUN) { cappedBacklog = accountIndex < accounts.size; break }; val response = PayloadClient.getPending(endpoint, key, account); val code = response.first; if (code !in 200..299) { if (PendingReminderPolicy.isRetryableHttpStatus(code)) transientFailure = true; continue }; val items = JSONObject(response.second).optJSONArray("items") ?: continue; for (i in 0 until items.length()) { if (notified >= MAX_NOTIFICATIONS_PER_RUN) { cappedBacklog = true; break }; val item = items.optJSONObject(i) ?: continue; val due = item.optJSONArray("due_targets_hours") ?: continue; if (due.length() == 0) continue; val dueTargets = mutableListOf<Double>(); for (j in 0 until due.length()) { val value = due.optDouble(j, -1.0); if (value > 0.0) dueTargets.add(value) }; val candidate = PendingReminderPolicy.candidate(account, item.optString("url"), item.optString("shortcode"), dueTargets) ?: continue; val dedupeKey = PendingReminderPolicy.dedupeKey(candidate); if (dedupeKey in shown) continue; notifyDue(candidate); shown.add(dedupeKey); shownChanged = true; notified += 1; if (!persistShownIfNeeded()) transientFailure = true; if (PendingReminderPolicy.shouldRetryForBacklog(notified, MAX_NOTIFICATIONS_PER_RUN, i < items.length() - 1 || accountIndex < accounts.lastIndex)) { cappedBacklog = true; break } }; if (cappedBacklog) break }; if (!persistShownIfNeeded()) transientFailure = true; if (notified > 0) TakeoffSound.play(TakeoffSound.Cue.REMINDER); if (transientFailure || cappedBacklog) Result.retry() else Result.success() } catch (_: Exception) { persistShownIfNeeded(); if (notified > 0) TakeoffSound.play(TakeoffSound.Cue.REMINDER); Result.retry() }
    }
    private fun notifyDue(candidate: PendingReminderCandidate) { val nm = applicationContext.getSystemService(NotificationManager::class.java); nm.createNotificationChannel(NotificationChannel(CHANNEL, "یادآوری هوشمند تیک‌آف", NotificationManager.IMPORTANCE_DEFAULT).apply { description = "یادآوری زمان مناسب برای Snapshot بعدی"; setSound(null, null); enableVibration(true); vibrationPattern = longArrayOf(0, 38, 42, 62) }); val armIntent = Intent(applicationContext, ReminderArmActivity::class.java).apply { data = Uri.parse(PendingReminderPolicy.armIntentIdentityUri(candidate)); putExtra(ReminderArmActivity.EXTRA_ACCOUNT, candidate.account); putExtra(ReminderArmActivity.EXTRA_URL, candidate.url) }; val requestBase = PendingReminderPolicy.requestCode(candidate); val armPending = PendingIntent.getActivity(applicationContext, requestBase, armIntent, PendingIntent.FLAG_UPDATE_CURRENT or PendingIntent.FLAG_IMMUTABLE); val openPending = PendingIntent.getActivity(applicationContext, requestBase xor 0x5a5a, Intent(Intent.ACTION_VIEW, Uri.parse(candidate.url)), PendingIntent.FLAG_UPDATE_CURRENT or PendingIntent.FLAG_IMMUTABLE); val label = if (candidate.targetHours >= 24) "${candidate.targetHours.toInt()/24} روز" else "${candidate.targetHours.toInt()} ساعت"; val notification = NotificationCompat.Builder(applicationContext, CHANNEL).setSmallIcon(android.R.drawable.ic_popup_reminder).setContentTitle("یک Snapshot تازه ارزش دارد").setContentText("$label گذشته • ریلز ${candidate.shortcode} در @${candidate.account}").setStyle(NotificationCompat.BigTextStyle().bigText("زمان ثبت دوباره آمار این ریلز رسیده. با «آماده‌سازی»، ابتدا همان پیج فعال می‌شود تا آمار کارفرماها با هم قاطی نشود.")).setContentIntent(armPending).addAction(0, "آماده‌سازی", armPending).addAction(0, "باز کردن ریلز", openPending).setAutoCancel(true).setSilent(true).build(); nm.notify(PendingReminderPolicy.notificationId(candidate), notification) }
}
